"""Pydantic models for MCP tool inputs and outputs."""

from mamba_mcp_sap_hana.models.hana import (
    CalcViewColumnInfo,
    CalcViewInfo,
    DescribeCalcViewInput,
    DescribeCalcViewOutput,
    DescribeProcedureInput,
    DescribeProcedureOutput,
    GetTableStoreTypeInput,
    GetTableStoreTypeOutput,
    ListCalcViewsInput,
    ListCalcViewsOutput,
    ListProceduresInput,
    ListProceduresOutput,
    ProcedureInfo,
    ProcedureParameterInfo,
    StoreTypeInfo,
)
from mamba_mcp_sap_hana.models.query import (
    ExecuteQueryInput,
    ExecuteQueryOutput,
    ExplainPlanNode,
    ExplainQueryInput,
    ExplainQueryOutput,
    QueryResult,
)
from mamba_mcp_sap_hana.models.relationships import (
    FindJoinPathInput,
    FindJoinPathOutput,
    ForeignKeyInfo,
    ForeignKeysOutput,
    GetForeignKeysInput,
    JoinPath,
    JoinStep,
)
from mamba_mcp_sap_hana.models.schema import (
    ColumnInfo,
    ConstraintInfo,
    DescribeTableInput,
    DescribeTableOutput,
    GetSampleRowsInput,
    IndexInfo,
    ListSchemasInput,
    ListSchemasOutput,
    ListTablesInput,
    ListTablesOutput,
    SampleRowsOutput,
    SchemaInfo,
    TableInfo,
)

__all__ = [
    # Schema models (Layer 1)
    "ListSchemasInput",
    "ListSchemasOutput",
    "SchemaInfo",
    "ListTablesInput",
    "ListTablesOutput",
    "TableInfo",
    "DescribeTableInput",
    "DescribeTableOutput",
    "ColumnInfo",
    "IndexInfo",
    "ConstraintInfo",
    "GetSampleRowsInput",
    "SampleRowsOutput",
    # Relationship models (Layer 2)
    "GetForeignKeysInput",
    "ForeignKeyInfo",
    "ForeignKeysOutput",
    "FindJoinPathInput",
    "FindJoinPathOutput",
    "JoinStep",
    "JoinPath",
    # Query models (Layer 3)
    "ExecuteQueryInput",
    "ExecuteQueryOutput",
    "QueryResult",
    "ExplainQueryInput",
    "ExplainQueryOutput",
    "ExplainPlanNode",
    # HANA-specific models (Layer 4)
    "CalcViewColumnInfo",
    "CalcViewInfo",
    "ListCalcViewsInput",
    "ListCalcViewsOutput",
    "GetTableStoreTypeInput",
    "GetTableStoreTypeOutput",
    "StoreTypeInfo",
    "DescribeCalcViewInput",
    "DescribeCalcViewOutput",
    "ProcedureParameterInfo",
    "ProcedureInfo",
    "ListProceduresInput",
    "ListProceduresOutput",
    "DescribeProcedureInput",
    "DescribeProcedureOutput",
]
